### ISSUE TITLE
Problem with Python 3 and when extending SeleniumLibrary with custom library. 

### ISSUE THREAD

**Issue by aaltat** [robotframework/PythonLibCore#5]
When I have this test case: 
```
*** Settings ***
Library           ./InheritSeleniumLibrary.py

*** Test Cases ***
Use InheritSeleniumLibrary Open Browser Keyword
    Open Browser     https://www.google.fi/
    ${capabilities} =    Get Browser Desired Capabilities
    Log    ${capabilities}
    [Teardown]    Close Browser
```
And when the `InheritSeleniumLibrary.py` is defined like this:
```
from robot.api import logger
from SeleniumLibrary import SeleniumLibrary
from SeleniumLibrary.base import keyword
from SeleniumLibrary.keywords import BrowserManagementKeywords


class InheritSeleniumLibrary(SeleniumLibrary):

    @keyword
    def get_browser_desired_capabilities(self):
        logger.info('Getting currently open browser desired capabilities')
        return self.driver.desired_capabilities
```
Then when I run the test with command: `python2 -m robot.run --loglevel trace inheritance.robot` test works OK, but when I run the test with command: `python3 -m robot.run --loglevel trace inheritance.robot` then the test fails with exception: 
```
22:00:49.234    FAIL    AttributeError: 'InheritSeleniumLibrary' object has no attribute 'driver'   
22:00:49.234    DEBUG   Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/SeleniumLibrary/__init__.py", line 344, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/SeleniumLibrary/base/robotlibcore.py", line 97, in run_keyword
    return self.keywords[name](*args, **kwargs)
  File "/home/godtdd/workspace/SeleniumLibrary/docs/extending/examples/inheritance/InheritSeleniumLibrary.py", line 18, in get_browser_desired_capabilities
    return self.driver.desired_capabilities
  File "/usr/local/lib/python3.6/dist-packages/SeleniumLibrary/base/robotlibcore.py", line 80, in __getattr__
    .format(type(self).__name__, name))
```
Here are the test suite and the library [test_suite.zip](https://github.com/robotframework/PythonLibCore/files/1604566/test_suite.zip)

**Comment by aaltat** [comment]
This is invalid issue, closing.
